#!/usr/bin/php
<?php
namespace Maiden;
$path = realpath(dirname(__FILE__));
ini_set("include_path", ".:{$path}:{$path}/lib:{$path}/modules/Piton/lib:" . PEAR_INSTALL_DIR);

require "Piton/AutoLoader.php";
\Piton\AutoLoader::register("{$path}/modules/Piton/lib/");
\Piton\AutoLoader::register("{$path}/lib/");

$maidenRunner = new MaidenRunner($logger = new \Piton\Log\DefaultLogger());

// Commandline options
$options = array(
	"-b" => function($args) use ($maidenRunner) {
		$maidenRunner->listTargets();
		return false;
	},
	"-l" => function($args) use ($maidenRunner) {
		$maidenRunner->listTargetDescriptions();
		return false;
	},
	"-v" => function($args) use ($maidenRunner, $logger) {
		$logger->setLevel($logger::LEVEL_DEBUG);
	}
);

array_shift($argv);

if (count($argv) == 0) {
	$argv[] = "-l";
}

$arguments = array();
foreach ($argv as $arg) {
	if (!isset($target) && isset($options[$arg])) {
		if ($options[$arg]($argv) === false) {
			exit;
		}
	} else {
		if (isset($target)) {
			$arguments[] = $arg;
		} else {
			$target = $arg;
		}
	}
}
// Run the chosen target
$maidenRunner->run($target, $arguments);
